export const endpoints = {
  auth: {
    login: "/auth/login",
    superAdminLogin: "/auth/super-admin-login",
    logout: "/auth/logout",
    register: "/auth/register",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    changePassword: "/auth/change-password",
  },
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userRole: (id: string) => `/admin/users/${id}/role`,
    aiModels: "/admin/ai-models",
    aiModel: (id: string) => `/admin/ai-models/${id}`,
    aiModelToggle: (id: string) => `/admin/ai-models/${id}/toggle`,
    companies: "/admin/companies",
    workflows: "/admin/workflows",
  },
  workspace: (slug: string) => `/workspaces/${slug}`,
  onboarding: {
    register: "/onboarding/register",
    login: "/onboarding/login",
    basicInfo: "/onboarding/basic-info",
    businessInfo: "/onboarding/business-info",
    selectModules: "/onboarding/select-modules",
    recommendations: "/onboarding/recommendations",
    modules: "/onboarding/modules",
    state: (userId: string) => `/onboarding/state/${userId}`,
  },
  hr: {
    employees: (companyId: string) => `/hr/${companyId}/employees`,
    employee: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}`,
    employeesExport: (companyId: string) => `/hr/${companyId}/employees/export`,
    employeesBulkImport: (companyId: string) => `/hr/${companyId}/employees/bulk-import`,
    employeeManager: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/manager`,
    orgChart: (companyId: string) => `/hr/${companyId}/org-chart`,
    departments: (companyId: string) => `/hr/${companyId}/departments`,
    roles: (companyId: string) => `/hr/${companyId}/roles`,
    role: (companyId: string, id: string) => `/hr/${companyId}/roles/${id}`,
    payrollRuns: (companyId: string) => `/hr/${companyId}/payroll/runs`,
    payrollRun: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}`,
    payrollRunStatus: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}/status`,
    payrollRunDownload: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}/download`,
    attendanceEmployee: (companyId: string, employeeId: string) =>
      `/hr/${companyId}/attendance/employees/${employeeId}`,
    attendanceEmployeeSummary: (companyId: string, employeeId: string) =>
      `/hr/${companyId}/attendance/employees/${employeeId}/summary`,
    attendanceCheckIn: (companyId: string) => `/hr/${companyId}/attendance/check-in`,
    attendanceCheckOut: (companyId: string) => `/hr/${companyId}/attendance/check-out`,
    attendanceRecord: (companyId: string, id: string) => `/hr/${companyId}/attendance/${id}`,
    leaveRequests: (companyId: string) => `/hr/${companyId}/leave/requests`,
    leaveRequest: (companyId: string, id: string) => `/hr/${companyId}/leave/requests/${id}`,
    leaveRequestStatus: (companyId: string, id: string) => `/hr/${companyId}/leave/requests/${id}/status`,
    leaveBalances: (companyId: string, employeeId: string) => `/hr/${companyId}/leave/balances/${employeeId}`,
    events: (companyId: string) => `/hr/${companyId}/events`,
    event: (companyId: string, id: string) => `/hr/${companyId}/events/${id}`,
    eventStatus: (companyId: string, id: string) => `/hr/${companyId}/events/${id}/status`,
    eventRsvp: (companyId: string, id: string) => `/hr/${companyId}/events/${id}/rsvp`,
    documentTypes: (companyId: string) => `/hr/${companyId}/documents/types`,
    documentTypeSubmissions: (companyId: string, typeId: string) =>
      `/hr/${companyId}/documents/types/${typeId}/submissions`,
    documentSubmissions: (companyId: string) => `/hr/${companyId}/documents/submissions`,
    documentSubmission: (companyId: string, id: string) => `/hr/${companyId}/documents/submissions/${id}`,
    documentSubmissionPreview: (companyId: string, id: string) =>
      `/hr/${companyId}/documents/submissions/${id}/preview`,
    documentSubmissionVerify: (companyId: string, id: string) =>
      `/hr/${companyId}/documents/submissions/${id}/verify`,
    documentRemind: (companyId: string) => `/hr/${companyId}/documents/remind`,
    policies: (companyId: string) => `/hr/${companyId}/policies`,
    policy: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}`,
    policyStatus: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/status`,
    policyAcknowledgments: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/acknowledgments`,
    policyAcknowledge: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/acknowledge`,
    policyRemind: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/remind`,
    policyExport: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/export`,
    settings: (companyId: string) => `/hr/${companyId}/settings`,
    settingsSection: (companyId: string, section: string) => `/hr/${companyId}/settings/${section}`,
    settingsReset: (companyId: string) => `/hr/${companyId}/settings/reset`,
    reportTemplates: (companyId: string) => `/hr/${companyId}/reports/templates`,
    reportGenerate: (companyId: string) => `/hr/${companyId}/reports/generate`,
    reportRuns: (companyId: string) => `/hr/${companyId}/reports/runs`,
    reportRun: (companyId: string, id: string) => `/hr/${companyId}/reports/runs/${id}`,
    reportRunDownload: (companyId: string, id: string) => `/hr/${companyId}/reports/runs/${id}/download`,
  },
  company: {
    departments: (companyId: string) => `/company/${companyId}/departments`,
    department: (companyId: string, deptId: string) => `/company/${companyId}/departments/${deptId}`,
    departmentTeams: (companyId: string, deptId: string) =>
      `/company/${companyId}/departments/${deptId}/teams`,
    departmentTeam: (companyId: string, deptId: string, teamId: string) =>
      `/company/${companyId}/departments/${deptId}/teams/${teamId}`,
    memberScope: (companyId: string, memberId: string) => `/company/${companyId}/members/${memberId}/scope`,
  },
};
