export const endpoints = {
  auth: {
    login: "/auth/login",
    superAdminLogin: "/auth/super-admin-login",
    logout: "/auth/logout",
    register: "/auth/register",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    changePassword: "/auth/change-password",
  },
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userRole: (id: string) => `/admin/users/${id}/role`,
    aiModels: "/admin/ai-models",
    aiModel: (id: string) => `/admin/ai-models/${id}`,
    aiModelToggle: (id: string) => `/admin/ai-models/${id}/toggle`,
    companies: "/admin/companies",
    workflows: "/admin/workflows",
  },
  workspace: (slug: string) => `/workspaces/${slug}`,
  onboarding: {
    register: "/onboarding/register",
    login: "/onboarding/login",
    basicInfo: "/onboarding/basic-info",
    businessInfo: "/onboarding/business-info",
    selectModules: "/onboarding/select-modules",
    recommendations: "/onboarding/recommendations",
    modules: "/onboarding/modules",
    state: (userId: string) => `/onboarding/state/${userId}`,
  },
  hr: {
    employees: (companyId: string) => `/hr/${companyId}/employees`,
    employee: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}`,
    employeesExport: (companyId: string) => `/hr/${companyId}/employees/export`,
    employeesBulkImport: (companyId: string) => `/hr/${companyId}/employees/bulk-import`,
    employeeManager: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/manager`,
    orgChart: (companyId: string) => `/hr/${companyId}/org-chart`,
    departments: (companyId: string) => `/hr/${companyId}/departments`,
    roles: (companyId: string) => `/hr/${companyId}/roles`,
    role: (companyId: string, id: string) => `/hr/${companyId}/roles/${id}`,
    payrollRuns: (companyId: string) => `/hr/${companyId}/payroll/runs`,
    payrollRun: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}`,
    payrollRunStatus: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}/status`,
    payrollRunDownload: (companyId: string, id: string) => `/hr/${companyId}/payroll/runs/${id}/download`,
    attendanceEmployee: (companyId: string, employeeId: string) =>
      `/hr/${companyId}/attendance/employees/${employeeId}`,
    attendanceEmployeeSummary: (companyId: string, employeeId: string) =>
      `/hr/${companyId}/attendance/employees/${employeeId}/summary`,
    attendanceCheckIn: (companyId: string) => `/hr/${companyId}/attendance/check-in`,
    attendanceCheckOut: (companyId: string) => `/hr/${companyId}/attendance/check-out`,
    attendanceRecord: (companyId: string, id: string) => `/hr/${companyId}/attendance/${id}`,
    leaveRequests: (companyId: string) => `/hr/${companyId}/leave/requests`,
    leaveRequest: (companyId: string, id: string) => `/hr/${companyId}/leave/requests/${id}`,
    leaveRequestStatus: (companyId: string, id: string) => `/hr/${companyId}/leave/requests/${id}/status`,
    leaveBalances: (companyId: string, employeeId: string) => `/hr/${companyId}/leave/balances/${employeeId}`,
    events: (companyId: string) => `/hr/${companyId}/events`,
    event: (companyId: string, id: string) => `/hr/${companyId}/events/${id}`,
    eventStatus: (companyId: string, id: string) => `/hr/${companyId}/events/${id}/status`,
    eventRsvp: (companyId: string, id: string) => `/hr/${companyId}/events/${id}/rsvp`,
    documentTypes: (companyId: string) => `/hr/${companyId}/documents/types`,
    documentTypeSubmissions: (companyId: string, typeId: string) =>
      `/hr/${companyId}/documents/types/${typeId}/submissions`,
    documentSubmissions: (companyId: string) => `/hr/${companyId}/documents/submissions`,
    documentSubmission: (companyId: string, id: string) => `/hr/${companyId}/documents/submissions/${id}`,
    documentSubmissionPreview: (companyId: string, id: string) =>
      `/hr/${companyId}/documents/submissions/${id}/preview`,
    documentSubmissionVerify: (companyId: string, id: string) =>
      `/hr/${companyId}/documents/submissions/${id}/verify`,
    documentRemind: (companyId: string) => `/hr/${companyId}/documents/remind`,
    policies: (companyId: string) => `/hr/${companyId}/policies`,
    policy: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}`,
    policyStatus: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/status`,
    policyAcknowledgments: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/acknowledgments`,
    policyAcknowledge: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/acknowledge`,
    policyRemind: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/remind`,
    policyExport: (companyId: string, id: string) => `/hr/${companyId}/policies/${id}/export`,
    settings: (companyId: string) => `/hr/${companyId}/settings`,
    settingsSection: (companyId: string, section: string) => `/hr/${companyId}/settings/${section}`,
    settingsReset: (companyId: string) => `/hr/${companyId}/settings/reset`,
    reportTemplates: (companyId: string) => `/hr/${companyId}/reports/templates`,
    reportGenerate: (companyId: string) => `/hr/${companyId}/reports/generate`,
    reportRuns: (companyId: string) => `/hr/${companyId}/reports/runs`,
    reportRun: (companyId: string, id: string) => `/hr/${companyId}/reports/runs/${id}`,
    reportRunDownload: (companyId: string, id: string) => `/hr/${companyId}/reports/runs/${id}/download`,
    dashboardSummary: (companyId: string) => `/hr/${companyId}/dashboard/summary`,
    dashboardSchedule: (companyId: string) => `/hr/${companyId}/dashboard/schedule`,
    dashboardTasks: (companyId: string) => `/hr/${companyId}/dashboard/tasks`,
    dashboardAttendanceSnapshot: (companyId: string) => `/hr/${companyId}/dashboard/attendance-snapshot`,
    recruitmentJobs: (companyId: string) => `/hr/${companyId}/recruitment/jobs`,
    recruitmentJob: (companyId: string, id: string) => `/hr/${companyId}/recruitment/jobs/${id}`,
    recruitmentCandidates: (companyId: string) => `/hr/${companyId}/recruitment/candidates`,
    recruitmentCandidateStage: (companyId: string, id: string) => `/hr/${companyId}/recruitment/candidates/${id}/stage`,
    recruitmentInterviews: (companyId: string) => `/hr/${companyId}/recruitment/interviews`,
    recruitmentInterview: (companyId: string, id: string) => `/hr/${companyId}/recruitment/interviews/${id}`,
    grievances: (companyId: string) => `/hr/${companyId}/grievances`,
    grievance: (companyId: string, id: string) => `/hr/${companyId}/grievances/${id}`,
    grievanceStatus: (companyId: string, id: string) => `/hr/${companyId}/grievances/${id}/status`,
    grievanceComments: (companyId: string, id: string) => `/hr/${companyId}/grievances/${id}/comments`,
    performanceDepartments: (companyId: string) => `/hr/${companyId}/performance/departments`,
    performanceTeams: (companyId: string) => `/hr/${companyId}/performance/teams`,
    performanceEmployees: (companyId: string) => `/hr/${companyId}/performance/employees`,
    performanceReviews: (companyId: string) => `/hr/${companyId}/performance/reviews`,
    performanceReview: (companyId: string, id: string) => `/hr/${companyId}/performance/reviews/${id}`,
    assets: (companyId: string) => `/hr/${companyId}/assets`,
    assetAssignments: (companyId: string) => `/hr/${companyId}/assets/assignments`,
    asset: (companyId: string, id: string) => `/hr/${companyId}/assets/${id}`,
    assetAssign: (companyId: string, id: string) => `/hr/${companyId}/assets/${id}/assign`,
    assetReturn: (companyId: string, id: string) => `/hr/${companyId}/assets/${id}/return`,
    activityLogs: (companyId: string) => `/hr/${companyId}/activity`,
    activityStats: (companyId: string) => `/hr/${companyId}/activity/stats`,
    attendanceRegularization: (companyId: string) => `/hr/${companyId}/attendance/regularization`,
    attendanceRegularizationStatus: (companyId: string, id: string) => `/hr/${companyId}/attendance/regularization/${id}/status`,
    attendanceRosters: (companyId: string) => `/hr/${companyId}/attendance/rosters`,
    attendanceRoster: (companyId: string, id: string) => `/hr/${companyId}/attendance/rosters/${id}`,
    attendanceRosterAssignments: (companyId: string, id: string) => `/hr/${companyId}/attendance/rosters/${id}/assignments`,
    attendanceOnBreak: (companyId: string) => `/hr/${companyId}/attendance/on-break`,
    attendanceBreakStart: (companyId: string) => `/hr/${companyId}/attendance/break/start`,
    attendanceBreakEnd: (companyId: string) => `/hr/${companyId}/attendance/break/end`,
    attendanceNotClockedIn: (companyId: string) => `/hr/${companyId}/attendance/not-clocked-in`,
    attendanceTodayStatus: (companyId: string) => `/hr/${companyId}/attendance/today-status`,
    salaryComponents: (companyId: string) => `/hr/${companyId}/payroll/salary-components`,
    employeeSalaryStructure: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/salary-structure`,
    reportsAnalytics: (companyId: string) => `/hr/${companyId}/reports/analytics`,
    employeeTimeline: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/timeline`,
    employeeSkills: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/skills`,
    employeeAssignedAssets: (companyId: string, id: string) => `/hr/${companyId}/employees/${id}/assigned-assets`,
    loans: (companyId: string) => `/hr/${companyId}/loans`,
    loan: (companyId: string, id: string) => `/hr/${companyId}/loans/${id}`,
    loanStatus: (companyId: string, id: string) => `/hr/${companyId}/loans/${id}/status`,
  },
  company: {
    departments: (companyId: string) => `/company/${companyId}/departments`,
    department: (companyId: string, deptId: string) => `/company/${companyId}/departments/${deptId}`,
    departmentTeams: (companyId: string, deptId: string) =>
      `/company/${companyId}/departments/${deptId}/teams`,
    departmentTeam: (companyId: string, deptId: string, teamId: string) =>
      `/company/${companyId}/departments/${deptId}/teams/${teamId}`,
    memberScope: (companyId: string, memberId: string) => `/company/${companyId}/members/${memberId}/scope`,
  },
  crm: {
    leads: "/crm/leads",
    lead: (id: string) => `/crm/leads/${id}`,
    leadActivities: (id: string) => `/crm/leads/${id}/activities`,
    dashboard: "/crm/dashboard",
    exportCsv: "/crm/leads/export/csv",
    bulkStage: "/crm/leads/bulk/stage",
    pipelines: "/crm/pipelines",
    pipeline: (id: string) => `/crm/pipelines/${id}`,
    stages: (pipelineId: string) => `/crm/pipelines/${pipelineId}/stages`,
    stage: (pipelineId: string, stageId: string) => `/crm/pipelines/${pipelineId}/stages/${stageId}`,
    reorderStages: (pipelineId: string) => `/crm/pipelines/${pipelineId}/stages/reorder`,
    deals: "/crm/deals",
    deal: (id: string) => `/crm/deals/${id}`,
    dealStage: (id: string) => `/crm/deals/${id}/stage`,
    dealsBulkStage: "/crm/deals/bulk/stage",
    tasks: "/crm/tasks",
    task: (id: string) => `/crm/tasks/${id}`,
    taskStatus: (id: string) => `/crm/tasks/${id}/status`,
    dialerQueue: "/crm/dialer/queue",
    dialerCall: "/crm/dialer/call",
    dialerDisposition: (id: string) => `/crm/dialer/calls/${id}/disposition`,
    dialerCalls: "/crm/dialer/calls",
    dialerSettings: "/crm/dialer/settings",
    settings: "/crm/settings",
    whatsappThreads: "/crm/whatsapp/threads",
    whatsappMessages: (id: string) => `/crm/whatsapp/threads/${id}/messages`,
    webhooks: "/crm/webhooks",
    webhook: (id: string) => `/crm/webhooks/${id}`,
    webhookTest: (id: string) => `/crm/webhooks/${id}/test`,
    layout: (entity: string) => `/crm/layouts/${entity}`,
    layoutFields: (entity: string) => `/crm/layouts/${entity}/fields`,
    layoutField: (id: string) => `/crm/layouts/fields/${id}`,
    facebookLeads: "/crm/integrations/facebook/leads",
    facebookSync: "/crm/integrations/facebook/sync",
    facebookConfig: "/crm/integrations/facebook/config",
    duplicates: "/crm/duplicates",
    duplicateMerge: "/crm/duplicates/merge",
    duplicateDismiss: "/crm/duplicates/dismiss",
    dashboardDeals: "/crm/dashboard/deals",
    reportsDealsAnalytics: "/crm/reports/deals/analytics",
    opportunities: "/crm/opportunities",
    contacts: "/crm/contacts",
    contact: (id: string) => `/crm/contacts/${id}`,
    leadsBulkImport: "/crm/leads/bulk-import",
  },
};
