export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    register: "/auth/register",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    changePassword: "/auth/change-password",
  },
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userRole: (id: string) => `/admin/users/${id}/role`,
    aiModels: "/admin/ai-models",
    aiModel: (id: string) => `/admin/ai-models/${id}`,
    aiModelToggle: (id: string) => `/admin/ai-models/${id}/toggle`,
    companies: "/admin/companies",
    workflows: "/admin/workflows",
  },
  workspace: (slug: string) => `/workspaces/${slug}`,
  onboarding: {
    register: "/onboarding/register",
    login: "/onboarding/login",
    basicInfo: "/onboarding/basic-info",
    businessInfo: "/onboarding/business-info",
    selectModules: "/onboarding/select-modules",
    recommendations: "/onboarding/recommendations",
    modules: "/onboarding/modules",
    state: (userId: string) => `/onboarding/state/${userId}`,
  },
};
