"use client";

import { useEffect } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Download, Loader2, X } from "lucide-react";

import {
  FORMAT_LABELS,
  RunStatusBadge,
} from "@/features/workspace/components/hrm/reports/hrm-report-runs-table";
import { HRM_REPORT_CATEGORIES } from "@/features/workspace/data/hrm-reports-demo";
import type { HrmReportFormat, HrmReportRun } from "@/types/hrm";

type Props = {
  open: boolean;
  run: HrmReportRun | null;
  downloading: boolean;
  onClose: () => void;
  onDownload: (run: HrmReportRun) => void;
};

export function HrmReportRunDetailDrawer({
  open,
  run,
  downloading,
  onClose,
  onDownload,
}: Props) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  const format =
    run && (run.format as HrmReportFormat) in FORMAT_LABELS
      ? (run.format as HrmReportFormat)
      : "csv";

  return (
    <AnimatePresence>
      {open && run ? (
        <>
          <motion.button
            type="button"
            aria-label="Close panel"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[110] bg-slate-900/40 backdrop-blur-[2px]"
            onClick={onClose}
          />
          <motion.aside
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 28, stiffness: 320 }}
            className="fixed inset-y-0 right-0 z-[111] flex w-full max-w-md flex-col border-l border-slate-200/80 bg-white shadow-2xl"
          >
            <div className="flex items-start justify-between gap-3 border-b border-slate-100 px-5 py-4">
              <div className="min-w-0">
                <p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">
                  Report run
                </p>
                <h2 className="mt-0.5 truncate text-lg font-bold text-slate-900">{run.name}</h2>
                <p className="mt-0.5 text-sm text-slate-500">{run.period}</p>
              </div>
              <button
                type="button"
                onClick={onClose}
                className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
                aria-label="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto px-5 py-4">
              <div className="mb-4">
                <RunStatusBadge status={run.status} />
              </div>

              <dl className="space-y-4">
                {[
                  {
                    label: "Category",
                    value:
                      HRM_REPORT_CATEGORIES.find((c) => c.id === run.category)?.label ??
                      run.category,
                  },
                  { label: "Generated by", value: run.generatedBy },
                  { label: "Generated at", value: run.generatedAt },
                  { label: "Export format", value: FORMAT_LABELS[format] },
                  { label: "File size", value: run.fileSize ?? "—" },
                ].map((item) => (
                  <div key={item.label}>
                    <dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">
                      {item.label}
                    </dt>
                    <dd className="mt-1 text-sm font-medium text-slate-900">{item.value}</dd>
                  </div>
                ))}
              </dl>

              {run.recordCount != null ? (
                <div className="mt-5 rounded-xl border border-[#191970]/15 bg-[#191970]/[0.04] px-4 py-3">
                  <p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">
                    Records included
                  </p>
                  <p className="mt-1 text-2xl font-bold tabular-nums text-[#191970]">
                    {run.recordCount}
                  </p>
                </div>
              ) : null}

              {run.status === "generating" ? (
                <div className="mt-5 flex items-center gap-2 rounded-xl border border-amber-200/80 bg-amber-50/50 px-4 py-3 text-sm text-amber-800">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating report — status updates automatically.
                </div>
              ) : null}

              {run.status === "failed" ? (
                <p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
                  Report generation failed. Try a different period or format from the report library.
                </p>
              ) : null}
            </div>

            {run.status === "ready" ? (
              <div className="border-t border-slate-100 px-5 py-4">
                <button
                  type="button"
                  onClick={() => onDownload(run)}
                  disabled={downloading}
                  className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-[#191970] text-sm font-semibold text-white hover:bg-[#12124a] disabled:opacity-50"
                >
                  {downloading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Downloading…
                    </>
                  ) : (
                    <>
                      <Download className="h-4 w-4" />
                      Download {String(run.format).toUpperCase()}
                    </>
                  )}
                </button>
              </div>
            ) : null}
          </motion.aside>
        </>
      ) : null}
    </AnimatePresence>
  );
}
